import mongoose from "mongoose";
import dns from "dns";
import dotenv from "dotenv";
import fs from "fs";
import path from "path";
if (process.platform === "win32") dns.setServers(["8.8.8.8", "8.8.4.4", "1.1.1.1"]);
const cwd = process.cwd();
const envPath = path.join(cwd, "info.dev.env");
dotenv.config({ path: fs.existsSync(envPath) ? envPath : path.join(cwd, "info.env") });
await mongoose.connect(process.env.MONGODB_URI, { serverSelectionTimeoutMS: 30000, family: 4 });
const col = mongoose.connection.db.collection("settings");
const before = await col.findOne({ key: "token-refresh-meta" });
console.log("ก่อน:", JSON.stringify(before));
await col.updateOne({ key: "token-refresh-meta" }, { $set: { value: { lastRefreshAt: Date.now() } } }, { upsert: true });
console.log("ตั้ง lastRefreshAt = ตอนนี้ แล้ว (scheduler จะข้าม refresh ตอนเทส)");
await mongoose.disconnect();
